# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stop_2 = QtWidgets.QPushButton(self.centralwidget)
        self.stop_2.setGeometry(QtCore.QRect(230, 300, 100, 50))
        self.stop_2.setObjectName("stop_2")
        self.run_2 = QtWidgets.QPushButton(self.centralwidget)
        self.run_2.setGeometry(QtCore.QRect(90, 300, 100, 50))
        self.run_2.setObjectName("run_2")
        self.reset_1 = QtWidgets.QPushButton(self.centralwidget)
        self.reset_1.setGeometry(QtCore.QRect(490, 220, 100, 50))
        self.reset_1.setObjectName("reset_1")
        self.stop_1 = QtWidgets.QPushButton(self.centralwidget)
        self.stop_1.setGeometry(QtCore.QRect(360, 220, 100, 50))
        self.stop_1.setObjectName("stop_1")
        self.reset_2 = QtWidgets.QPushButton(self.centralwidget)
        self.reset_2.setGeometry(QtCore.QRect(360, 300, 100, 50))
        self.reset_2.setObjectName("reset_2")
        self.read = QtWidgets.QTextEdit(self.centralwidget)
        self.read.setGeometry(QtCore.QRect(80, 470, 661, 81))
        self.read.setObjectName("read")
        self.run_1 = QtWidgets.QPushButton(self.centralwidget)
        self.run_1.setGeometry(QtCore.QRect(90, 220, 100, 50))
        self.run_1.setIconSize(QtCore.QSize(20, 20))
        self.run_1.setAutoRepeatDelay(300)
        self.run_1.setObjectName("run_1")
        self.run_reboot = QtWidgets.QPushButton(self.centralwidget)
        self.run_reboot.setGeometry(QtCore.QRect(230, 220, 100, 50))
        self.run_reboot.setObjectName("run_reboot")
        self.connect_reboot = QtWidgets.QPushButton(self.centralwidget)
        self.connect_reboot.setGeometry(QtCore.QRect(100, 50, 93, 28))
        self.connect_reboot.setObjectName("connect_reboot")
        self.input_v = QtWidgets.QTextEdit(self.centralwidget)
        self.input_v.setGeometry(QtCore.QRect(310, 50, 71, 31))
        self.input_v.setObjectName("input_v")
        self.set_v = QtWidgets.QPushButton(self.centralwidget)
        self.set_v.setGeometry(QtCore.QRect(380, 50, 81, 31))
        self.set_v.setObjectName("set_v")
        self.clean_err = QtWidgets.QPushButton(self.centralwidget)
        self.clean_err.setGeometry(QtCore.QRect(90, 380, 100, 50))
        self.clean_err.setObjectName("clean_err")
        self.read_err = QtWidgets.QPushButton(self.centralwidget)
        self.read_err.setGeometry(QtCore.QRect(490, 300, 100, 50))
        self.read_err.setObjectName("read_err")
        self.read_belt = QtWidgets.QPushButton(self.centralwidget)
        self.read_belt.setGeometry(QtCore.QRect(630, 370, 120, 50))
        self.read_belt.setObjectName("read_belt")
        self.read_gripper = QtWidgets.QPushButton(self.centralwidget)
        self.read_gripper.setGeometry(QtCore.QRect(630, 270, 120, 50))
        self.read_gripper.setObjectName("read_gripper")
        self.run_cylinder = QtWidgets.QPushButton(self.centralwidget)
        self.run_cylinder.setGeometry(QtCore.QRect(230, 380, 100, 50))
        self.run_cylinder.setObjectName("run_cylinder")
        self.reset_cylinder = QtWidgets.QPushButton(self.centralwidget)
        self.reset_cylinder.setGeometry(QtCore.QRect(360, 380, 100, 50))
        self.reset_cylinder.setObjectName("reset_cylinder")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.input_v, self.run_2)
        MainWindow.setTabOrder(self.run_2, self.reset_2)
        MainWindow.setTabOrder(self.reset_2, self.stop_2)
        MainWindow.setTabOrder(self.stop_2, self.read)
        MainWindow.setTabOrder(self.read, self.set_v)
        MainWindow.setTabOrder(self.set_v, self.connect_reboot)
        MainWindow.setTabOrder(self.connect_reboot, self.stop_1)
        MainWindow.setTabOrder(self.stop_1, self.reset_1)
        MainWindow.setTabOrder(self.reset_1, self.run_reboot)
        MainWindow.setTabOrder(self.run_reboot, self.run_1)
        MainWindow.setTabOrder(self.run_1, self.clean_err)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stop_2.setText(_translate("MainWindow", "停止程序B"))
        self.run_2.setText(_translate("MainWindow", "执行程序B"))
        self.reset_1.setText(_translate("MainWindow", "重置程序A"))
        self.stop_1.setText(_translate("MainWindow", "停止程序A"))
        self.reset_2.setText(_translate("MainWindow", "重置程序B"))
        self.read.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.run_1.setText(_translate("MainWindow", "执行程序A"))
        self.run_reboot.setText(_translate("MainWindow", "启动机器人"))
        self.connect_reboot.setText(_translate("MainWindow", "连接机器人"))
        self.input_v.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">10</span></p></body></html>"))
        self.set_v.setText(_translate("MainWindow", "速度设置"))
        self.clean_err.setText(_translate("MainWindow", "错误清除"))
        self.read_err.setText(_translate("MainWindow", "错误读取"))
        self.read_belt.setText(_translate("MainWindow", "读取皮带速度"))
        self.read_gripper.setText(_translate("MainWindow", "自动"))
        self.run_cylinder.setText(_translate("MainWindow", "气缸作动"))
        self.reset_cylinder.setText(_translate("MainWindow", "气缸复位"))
